import { ISOCountryCode, ISOLanguageCode, LanguageInfo, WorldRegion } from "./types";

export const languageInfo: LanguageInfo[] = [
    {   name: "Afrikaans",
        general: true,
        code: ISOLanguageCode.Afrikaans,
        popular: true,
        flag: ISOCountryCode.SouthAfrica
    },
    {   name: "Albanian",
        general: true,
        code: ISOLanguageCode.Albanian,
        popular: true,
        flag: ISOCountryCode.Albania
    },
    {   name: "Amharic",
        general: true,
        code: ISOLanguageCode.Amharic,
        flag: ISOCountryCode.Ethiopia
    },
    {   name: "Arabic",
        general: true,
        code: ISOLanguageCode.Arabic,
        popular: true,
        flag: ISOCountryCode.SaudiArabia
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Algeria,
        code: ISOLanguageCode.ArabicAlgeria,
        flag: ISOCountryCode.Algeria
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Bahrain,
        code: ISOLanguageCode.ArabicBahrain,
        flag: ISOCountryCode.Bahrain
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Egypt,
        code: ISOLanguageCode.ArabicEgypt,
        flag: ISOCountryCode.Egypt
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Iraq,
        code: ISOLanguageCode.ArabicIraq,
        flag: ISOCountryCode.Iraq
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Jordan,
        code: ISOLanguageCode.ArabicJordan,
        flag: ISOCountryCode.Jordan
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Kuwait,
        code: ISOLanguageCode.ArabicKuwait,
        flag: ISOCountryCode.Kuwait
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Lebanon,
        code: ISOLanguageCode.ArabicLebanon,
        flag: ISOCountryCode.Lebanon
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Libya,
        code: ISOLanguageCode.ArabicLibya,
        flag: ISOCountryCode.Libya
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Morocco,
        code: ISOLanguageCode.ArabicMorocco,
        flag: ISOCountryCode.Morocco
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Oman,
        code: ISOLanguageCode.ArabicOman,
        flag: ISOCountryCode.Oman
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Qatar,
        code: ISOLanguageCode.ArabicQatar,
        flag: ISOCountryCode.Qatar
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.SaudiArabia,
        code: ISOLanguageCode.ArabicSaudiArabia,
        flag: ISOCountryCode.SaudiArabia
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Syria,
        code: ISOLanguageCode.ArabicSyria,
        flag: ISOCountryCode.Syria
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Tunisia,
        code: ISOLanguageCode.ArabicTunisia,
        flag: ISOCountryCode.Tunisia
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.UnitedArabEmirates,
        code: ISOLanguageCode.ArabicUnitedArabEmirates,
        flag: ISOCountryCode.UnitedArabEmirates
    },
    {   name: "Arabic",
        countryCode: ISOCountryCode.Yemen,
        code: ISOLanguageCode.ArabicYemen,
        flag: ISOCountryCode.Yemen
    },
    {   name: "Armenian",
        general: true,
        code: ISOLanguageCode.Armenian,
        popular: true,
        flag: ISOCountryCode.Armenia
    },
    {   name: "Assamese",
        general: true,
        code: ISOLanguageCode.Assamese,
        flag: ISOCountryCode.India
    },
    {   name: "Azeri",
        general: true,
        code: ISOLanguageCode.Azeri,
        flag: ISOCountryCode.Azerbaijan
    },
    {   name: "Basque",
        general: true,
        code: ISOLanguageCode.Basque,
        flag: ISOCountryCode.Spain
    },
    {   name: "Belarusian",
        general: true,
        code: ISOLanguageCode.Belarusian,
        popular: true,
        flag: ISOCountryCode.Belarus
    },
    {   name: "Bengali",
        general: true,
        code: ISOLanguageCode.Bengali,
        popular: true,
        flag: ISOCountryCode.Bangladesh
    },
    {   name: "Bosnian",
        general: true,
        code: ISOLanguageCode.Bosnian,
        popular: true,
        flag: ISOCountryCode.BosniaAndHerzegovina
    },
    {   name: "Bulgarian",
        general: true,
        code: ISOLanguageCode.Bulgarian,
        popular: true,
        flag: ISOCountryCode.Bulgaria
    },
    {   name: "Burmese",
        general: true,
        code: ISOLanguageCode.Burmese,
        flag: ISOCountryCode.Myanmar
    },
    {   name: "Catalan",
        general: true,
        code: ISOLanguageCode.Catalan,
        flag: ISOCountryCode.Catalonia
    },
    {   name: "Chinese",
        general: true,
        code: ISOLanguageCode.Chinese,
        popular: true,
        flag: ISOCountryCode.China
    },
    {   name: "Chinese",
        countryCode: ISOCountryCode.China,
        code: ISOLanguageCode.ChineseChina,
        popular: true,
        flag: ISOCountryCode.China
    },
    {   name: "Chinese",
        countryCode: ISOCountryCode.HongKong,
        code: ISOLanguageCode.ChineseHongKong,
        popular: true,
        flag: ISOCountryCode.HongKong
    },
    {   name: "Chinese",
        countryCode: ISOCountryCode.Macau,
        code: ISOLanguageCode.ChineseMacau,
        popular: true,
        flag: ISOCountryCode.Macau
    },
    {   name: "Chinese",
        countryCode: ISOCountryCode.Singapore,
        code: ISOLanguageCode.ChineseSingapore,
        popular: true,
        flag: ISOCountryCode.Singapore
    },
    {   name: "Chinese",
        countryCode: ISOCountryCode.Taiwan,
        code: ISOLanguageCode.ChineseTaiwan,
        popular: true,
        flag: ISOCountryCode.Taiwan
    },
    {   name: "Croatian",
        general: true,
        code: ISOLanguageCode.Croatian,
        popular: true,
        flag: ISOCountryCode.Croatia
    },
    {   name: "Czech",
        general: true,
        code: ISOLanguageCode.Czech,
        popular: true,
        flag: ISOCountryCode.Czechia
    },
    {   name: "Danish",
        general: true,
        code: ISOLanguageCode.Danish,
        popular: true,
        flag: ISOCountryCode.Denmark
    },
    {   name: "Dutch",
        general: true,
        code: ISOLanguageCode.Dutch,
        popular: true,
        flag: ISOCountryCode.Netherlands
    },
    {   name: "Dutch",
        countryCode: ISOCountryCode.Belgium,
        code: ISOLanguageCode.DutchBelgium,
        flag: ISOCountryCode.Belgium
    },
    {   name: "Dutch",
        countryCode: ISOCountryCode.Netherlands,
        code: ISOLanguageCode.DutchNetherlands,
        flag: ISOCountryCode.Netherlands
    },
    {   name: "Dzongkha",
        general: true,
        code: ISOLanguageCode.Dzongkha,
        flag: ISOCountryCode.Bhutan
    },
    {   name: "English",
        general: true,
        code: ISOLanguageCode.English,
        popular: true,
        flag: ISOCountryCode.UnitedKingdom
    },
    {   name: "English",
        countryCode: ISOCountryCode.Australia,
        code: ISOLanguageCode.EnglishAustralia,
        popular: true,
        flag: ISOCountryCode.Australia
    },
    {   name: "English",
        countryCode: ISOCountryCode.Belize,
        code: ISOLanguageCode.EnglishBelize,
        flag: ISOCountryCode.Belize
    },
    {   name: "English",
        countryCode: ISOCountryCode.Canada,
        code: ISOLanguageCode.EnglishCanada,
        popular: true,
        flag: ISOCountryCode.Canada
    },
    {   name: "English",
        countryCode: ISOCountryCode.India,
        code: ISOLanguageCode.EnglishIndia,
        popular: true,
        flag: ISOCountryCode.India
    },
    {   name: "English",
        countryCode: ISOCountryCode.Ireland,
        code: ISOLanguageCode.EnglishIreland,
        popular: true,
        flag: ISOCountryCode.Ireland
    },
    {   name: "English",
        countryCode: ISOCountryCode.Jamaica,
        code: ISOLanguageCode.EnglishJamaica,
        popular: true,
        flag: ISOCountryCode.Jamaica
    },
    {   name: "English",
        countryCode: ISOCountryCode.NewZealand,
        code: ISOLanguageCode.EnglishNewZealand,
        popular: true,
        flag: ISOCountryCode.NewZealand
    },
    {   name: "English",
        countryCode: ISOCountryCode.Philippines,
        code: ISOLanguageCode.EnglishPhilippines,
        popular: true,
        flag: ISOCountryCode.Philippines
    },
    {   name: "English",
        countryCode: ISOCountryCode.SouthAfrica,
        code: ISOLanguageCode.EnglishAfrica,
        popular: true,
        flag: ISOCountryCode.SouthAfrica
    },
    {   name: "English",
        countryCode: ISOCountryCode.TrinidadAndTobago,
        code: ISOLanguageCode.EnglishTrinidadAndTobago,
        flag: ISOCountryCode.TrinidadAndTobago
    },
    {   name: "English",
        countryCode: ISOCountryCode.UnitedKingdom,
        code: ISOLanguageCode.EnglishGreatBritain,
        popular: true,
        flag: ISOCountryCode.UnitedKingdom
    },
    {   name: "English",
        countryCode: ISOCountryCode.UnitedStatesOfAmerica,
        code: ISOLanguageCode.EnglishUnitedStatesOfAmerica,
        popular: true,
        flag: ISOCountryCode.UnitedStatesOfAmerica
    },
    {   name: "English",
        countryCode: ISOCountryCode.Zimbabwe,
        code: ISOLanguageCode.EnglishZimbabwe,
        popular: true,
        flag: ISOCountryCode.Zimbabwe
    },
    {   name: "English",
        countryCode: WorldRegion.Caribbean,
        code: ISOLanguageCode.EnglishCaribbean,
        popular: true,
        flag: ISOCountryCode.Anguilla
    },
    {   name: "Estonian",
        general: true,
        code: ISOLanguageCode.Estonian,
        popular: true,
        flag: ISOCountryCode.Estonia
    },
    {   name: "Faroese",
        general: true,
        code: ISOLanguageCode.Faroese,
        flag: ISOCountryCode.FaroeIslands
    },
    {   name: "Farsi",
        general: true,
        code: ISOLanguageCode.Persian,
        flag: ISOCountryCode.Iran
    },
    {   name: "Finnish",
        general: true,
        code: ISOLanguageCode.Finnish,
        popular: true,
        flag: ISOCountryCode.Finland
    },
    {   name: "French",
        general: true,
        code: ISOLanguageCode.French,
        popular: true,
        flag: ISOCountryCode.France
    },
    {   name: "French",
        countryCode: ISOCountryCode.Belgium,
        code: ISOLanguageCode.FrenchBelgium,
        popular: true,
        flag: ISOCountryCode.Belgium
    },
    {   name: "French",
        countryCode: ISOCountryCode.Canada,
        code: ISOLanguageCode.FrenchCanada,
        popular: true,
        flag: ISOCountryCode.Canada
    },
    {   name: "French",
        countryCode: ISOCountryCode.France,
        code: ISOLanguageCode.FrenchFrance,
        popular: true,
        flag: ISOCountryCode.France
    },
    {   name: "French",
        countryCode: ISOCountryCode.India,
        code: ISOLanguageCode.FrenchIndia,
        popular: true,
        flag: ISOCountryCode.India
    },
    {   name: "French",
        countryCode: ISOCountryCode.IvoryCoast,
        code: ISOLanguageCode.FrenchIvoryCoast,
        flag: ISOCountryCode.IvoryCoast
    },
    {   name: "French",
        countryCode: ISOCountryCode.Luxembourg,
        code: ISOLanguageCode.FrenchLuxembourg,
        popular: true,
        flag: ISOCountryCode.Luxembourg
    },
    {   name: "French",
        countryCode: ISOCountryCode.Mali,
        code: ISOLanguageCode.FrenchMali,
        flag: ISOCountryCode.Mali
    },
    {   name: "French",
        countryCode: ISOCountryCode.Monaco,
        code: ISOLanguageCode.FrenchMonaco,
        popular: true,
        flag: ISOCountryCode.Monaco
    },
    {   name: "French",
        countryCode: ISOCountryCode.Morocco,
        code: ISOLanguageCode.FrenchMorocco,
        popular: true,
        flag: ISOCountryCode.Morocco
    },
    {   name: "French",
        countryCode: ISOCountryCode.RepublicOfCongo,
        code: ISOLanguageCode.FrenchRepublicOfCongo,
        flag: ISOCountryCode.RepublicOfCongo
    },
    {   name: "French",
        countryCode: ISOCountryCode.Senegal,
        code: ISOLanguageCode.FrenchSenegal,
        flag: ISOCountryCode.Senegal
    },
    {   name: "French",
        countryCode: ISOCountryCode.Switzerland,
        code: ISOLanguageCode.FrenchSwitzerland,
        popular: true,
        flag: ISOCountryCode.Switzerland
    },
    {   name: "Gaelic",
        countryCode: ISOCountryCode.Ireland,
        code: ISOLanguageCode.GaelicIreland,
        flag: ISOCountryCode.Ireland
    },
    {   name: "Gaelic",
        countryCode: ISOCountryCode.UnitedKingdom,
        code: ISOLanguageCode.GaelicScotland,
        flag: ISOCountryCode.Scotland
    },
    {   name: "Galician",
        general: true,
        code: ISOLanguageCode.Galician,
        flag: ISOCountryCode.Spain
    },
    {   name: "Georgian",
        general: true,
        code: ISOLanguageCode.Georgian,
        popular: true,
        flag: ISOCountryCode.Georgia
    },
    {   name: "German",
        general: true,
        code: ISOLanguageCode.German,
        popular: true,
        flag: ISOCountryCode.Germany
    },
    {   name: "German",
        countryCode: ISOCountryCode.Austria,
        code: ISOLanguageCode.GermanAustria,
        popular: true,
        flag: ISOCountryCode.Austria
    },
    {   name: "German",
        countryCode: ISOCountryCode.Germany,
        code: ISOLanguageCode.GermanGermany,
        popular: true,
        flag: ISOCountryCode.Germany
    },
    {   name: "German",
        countryCode: ISOCountryCode.Liechtenstein,
        code: ISOLanguageCode.GermanLiechtenstein,
        flag: ISOCountryCode.Liechtenstein
    },
    {   name: "German",
        countryCode: ISOCountryCode.Luxembourg,
        code: ISOLanguageCode.GermanLuxembourg,
        flag: ISOCountryCode.Luxembourg
    },
    {   name: "German",
        countryCode: ISOCountryCode.Switzerland,
        code: ISOLanguageCode.GermanSwitzerland,
        popular: true,
        flag: ISOCountryCode.Switzerland
    },
    {   name: "Greek",
        general: true,
        code: ISOLanguageCode.Greek,
        popular: true,
        flag: ISOCountryCode.Greece
    },
    {   name: "Greenlandic",
        general: true,
        code: ISOLanguageCode.Greenlandic,
        flag: ISOCountryCode.Greenland
    },
    {   name: "Guarani",
        code: ISOLanguageCode.Guarani,
        popular: true,
        flag: ISOCountryCode.Paraguay
    },
    {   name: "Gujarati",
        general: true,
        code: ISOLanguageCode.Gujarati,
        flag: ISOCountryCode.India
    },
    {   name: "Hebrew",
        general: true,
        code: ISOLanguageCode.Hebrew,
        popular: true,
        flag: ISOCountryCode.Israel
    },
    {   name: "Hindi",
        general: true,
        code: ISOLanguageCode.Hindi,
        popular: true,
        flag: ISOCountryCode.India
    },
    {   name: "Hungarian",
        general: true,
        code: ISOLanguageCode.Hungarian,
        popular: true,
        flag: ISOCountryCode.Hungary
    },
    {   name: "Icelandic",
        general: true,
        code: ISOLanguageCode.Icelandic,
        popular: true,
        flag: ISOCountryCode.Iceland
    },
    {   name: "Igbo",
        general: true,
        code: ISOLanguageCode.Igbo,
        flag: ISOCountryCode.Nigeria
    },
    {   name: "Indonesian",
        general: true,
        code: ISOLanguageCode.Indonesian,
        popular: true,
        flag: ISOCountryCode.Indonesia
    },
    {   name: "Irish",
        general: true,
        code: ISOLanguageCode.Irish,
        popular: true,
        flag: ISOCountryCode.Ireland
    },
    {   name: "Italian",
        general: true,
        code: ISOLanguageCode.Italian,
        popular: true,
        flag: ISOCountryCode.Italy
    },
    {   name: "Italian",
        countryCode: ISOCountryCode.Italy,
        code: ISOLanguageCode.ItalianItaly,
        flag: ISOCountryCode.Italy
    },
    {   name: "Italian",
        countryCode: ISOCountryCode.Switzerland,
        code: ISOLanguageCode.ItalianSwitzerland,
        flag: ISOCountryCode.Switzerland
    },
    {   name: "Japanese",
        general: true,
        code: ISOLanguageCode.Japanese,
        popular: true,
        flag: ISOCountryCode.Japan
    },
    {   name: "Kannada",
        general: true,
        code: ISOLanguageCode.Kannada,
        flag: ISOCountryCode.India
    },
    {   name: "Kazakh",
        general: true,
        code: ISOLanguageCode.Kazakh,
        popular: true,
        flag: ISOCountryCode.Kazakhstan
    },
    {   name: "Khmer",
        general: true,
        code: ISOLanguageCode.Khmer,
        flag: ISOCountryCode.Cambodia
    },
    {   name: "Korean",
        general: true,
        code: ISOLanguageCode.Korean,
        popular: true,
        flag: ISOCountryCode.SouthKorea
    },
    {   name: "Kyrgyz",
        general: true,
        code: ISOLanguageCode.Kyrgyz,
        popular: true,
        flag: ISOCountryCode.Kyrgyzstan
    },
    {   name: "Lao",
        general: true,
        code: ISOLanguageCode.Lao,
        popular: true,
        flag: ISOCountryCode.Laos
    },
    {   name: "Latin",
        general: true,
        code: ISOLanguageCode.Latin,
        popular: true,
        flag: ISOCountryCode.Vatican
    },
    {   name: "Latvian",
        general: true,
        code: ISOLanguageCode.Latvian,
        popular: true,
        flag: ISOCountryCode.Latvia
    },
    {   name: "Lithuanian",
        general: true,
        code: ISOLanguageCode.Lithuanian,
        popular: true,
        flag: ISOCountryCode.Lithuania
    },
    {   name: "Luxembourgish",
        general: true,
        code: ISOLanguageCode.Luxembourgish,
        popular: true,
        flag: ISOCountryCode.Luxembourg
    },
    {   name: "Macedonian",
        general: true,
        code: ISOLanguageCode.Macedonian,
        popular: true,
        flag: ISOCountryCode.NorthMacedonia
    },
    {   name: "Malay",
        general: true,
        code: ISOLanguageCode.Malay,
        flag: ISOCountryCode.Malaysia
    },
    {   name: "Malay",
        countryCode: ISOCountryCode.BruneiDarussalam,
        code: ISOLanguageCode.MalayBrunei,
        flag: ISOCountryCode.BruneiDarussalam
    },
    {   name: "Malay",
        countryCode: ISOCountryCode.Malaysia,
        code: ISOLanguageCode.MalayMalaysia,
        flag: ISOCountryCode.Malaysia
    },
    {   name: "Malayalam",
        general: true,
        code: ISOLanguageCode.Malayalam,
        flag: ISOCountryCode.India
    },
    {   name: "Maldivian",
        general: true,
        code: ISOLanguageCode.Maldivian,
        popular: true,
        flag: ISOCountryCode.Maldives
    },
    {   name: "Maltese",
        general: true,
        code: ISOLanguageCode.Maltese,
        popular: true,
        flag: ISOCountryCode.Malta
    },
    {   name: "Maori",
        general: true,
        code: ISOLanguageCode.Maori,
        flag: ISOCountryCode.NewZealand
    },
    {   name: "Marathi",
        general: true,
        code: ISOLanguageCode.Marathi,
        flag: ISOCountryCode.India
    },
    {   name: "Mongolian",
        general: true,
        code: ISOLanguageCode.Mongolian,
        popular: true,
        flag: ISOCountryCode.Mongolia
    },
    {   name: "Nepali",
        general: true,
        code: ISOLanguageCode.Nepali,
        popular: true,
        flag: ISOCountryCode.Nepal
    },
    {   name: "Norwegian",
        general: true,
        code: ISOLanguageCode.Norwegian,
        popular: true,
        flag: ISOCountryCode.Norway
    },
    {   name: "Oriya",
        general: true,
        code: ISOLanguageCode.Oriya,
        flag: ISOCountryCode.India,
    },
    {   name: "Pashto",
        general: true,
        code: ISOLanguageCode.Pashto,
        flag: ISOCountryCode.Afghanistan
    },
    {   name: "Polish",
        general: true,
        code: ISOLanguageCode.Polish,
        popular: true,
        flag: ISOCountryCode.Poland
    },
    {   name: "Portuguese",
        general: true,
        code: ISOLanguageCode.Portuguese,
        popular: true,
        flag: ISOCountryCode.Portugal
    },
    {   name: "Portuguese",
        countryCode: ISOCountryCode.Brazil,
        code: ISOLanguageCode.PortugueseBrazil,
        popular: true,
        flag: ISOCountryCode.Brazil
    },
    {   name: "Portuguese",
        countryCode: ISOCountryCode.Portugal,
        code: ISOLanguageCode.PortuguesePortugal,
        flag: ISOCountryCode.Portugal
    },
    {   name: "Punjabi",
        general: true,
        code: ISOLanguageCode.Punjabi,
        flag: ISOCountryCode.India
    },
    {   name: "Romanian",
        general: true,
        code: ISOLanguageCode.Romanian,
        popular: true,
        flag: ISOCountryCode.Romania
    },
    {   name: "Romanian",
        countryCode: ISOCountryCode.Moldova,
        code: ISOLanguageCode.RomanianMoldova,
        flag: ISOCountryCode.Moldova
    },
    {   name: "Russian",
        general: true,
        code: ISOLanguageCode.Russian,
        popular: true,
        flag: ISOCountryCode.RussianFederation
    },
    {   name: "Russian",
        countryCode: ISOCountryCode.Moldova,
        code: ISOLanguageCode.RussianMoldova,
        flag: ISOCountryCode.Moldova
    },
    {   name: "Samoan",
        general: true,
        code: ISOLanguageCode.Samoan,
        flag: ISOCountryCode.Samoa
    },
    {   name: "Serbian",
        general: true,
        code: ISOLanguageCode.Serbian,
        popular: true,
        flag: ISOCountryCode.Serbia
    },
    {   name: "Sindhi",
        general: true,
        code: ISOLanguageCode.Sindhi,
        flag: ISOCountryCode.India
    },
    {   name: "Sinhalese",
        general: true,
        code: ISOLanguageCode.Sinhalese,
        flag: ISOCountryCode.SriLanka
    },
    {   name: "Slovak",
        general: true,
        code: ISOLanguageCode.Slovak,
        popular: true,
        flag: ISOCountryCode.Slovakia
    },
    {   name: "Slovenian",
        general: true,
        code: ISOLanguageCode.Slovenian,
        popular: true,
        flag: ISOCountryCode.Slovenia
    },
    {   name: "Somali",
        general: true,
        code: ISOLanguageCode.Somali,
        popular: true,
        flag: ISOCountryCode.Somalia
    },
    {   name: "Sotho",
        general: true,
        code: ISOLanguageCode.Sotho,
        flag: ISOCountryCode.Lesotho
    },
    {   name: "Spanish",
        general: true,
        code: ISOLanguageCode.Spanish,
        popular: true,
        flag: ISOCountryCode.Spain
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Argentina,
        code: ISOLanguageCode.SpanishArgentina,
        flag: ISOCountryCode.Argentina
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Bolivia,
        code: ISOLanguageCode.SpanishBolivia,
        flag: ISOCountryCode.Bolivia
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Chile,
        code: ISOLanguageCode.SpanishChile,
        flag: ISOCountryCode.Chile
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Colombia,
        code: ISOLanguageCode.SpanishColombia,
        flag: ISOCountryCode.Colombia
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.CostaRica,
        code: ISOLanguageCode.SpanishCostaRica,
        flag: ISOCountryCode.CostaRica
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.DominicanRepublic,
        code: ISOLanguageCode.SpanishDominicanRepublic,
        flag: ISOCountryCode.DominicanRepublic
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Ecuador,
        code: ISOLanguageCode.SpanishEcuador,
        flag: ISOCountryCode.Ecuador
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.ElSalvador,
        code: ISOLanguageCode.SpanishElSalvador,
        flag: ISOCountryCode.ElSalvador
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Guatemala,
        code: ISOLanguageCode.SpanishGuatemala,
        flag: ISOCountryCode.Guatemala
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Honduras,
        code: ISOLanguageCode.SpanishHonduras,
        flag: ISOCountryCode.Honduras
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Mexico,
        code: ISOLanguageCode.SpanishMexico,
        popular: true,
        flag: ISOCountryCode.Mexico
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Nicaragua,
        code: ISOLanguageCode.SpanishNicaragua,
        flag: ISOCountryCode.Nicaragua
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Panama,
        code: ISOLanguageCode.SpanishPanama,
        flag: ISOCountryCode.Panama
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Paraguay,
        code: ISOLanguageCode.SpanishParaguay,
        flag: ISOCountryCode.Paraguay
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Peru,
        code: ISOLanguageCode.SpanishPeru,
        flag: ISOCountryCode.Peru
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.PuertoRico,
        code: ISOLanguageCode.SpanishPuertoRico,
        flag: ISOCountryCode.PuertoRico
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Spain,
        code: ISOLanguageCode.SpanishSpain,
        popular: true,
        flag: ISOCountryCode.Spain
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Uruguay,
        code: ISOLanguageCode.SpanishUruguay,
        flag: ISOCountryCode.Uruguay
    },
    {   name: "Spanish",
        countryCode: ISOCountryCode.Venezuela,
        code: ISOLanguageCode.SpanishVenezuela,
        flag: ISOCountryCode.Venezuela
    },
    {   name: "Swahili",
        general: true,
        code: ISOLanguageCode.Swahili,
        popular: true,
        flag: ISOCountryCode.Tanzania
    },
    {   name: "Swazi",
        general: true,
        code: ISOLanguageCode.Swazi,
        flag: ISOCountryCode.Eswatini
    },
    {   name: "Swedish",
        general: true,
        code: ISOLanguageCode.Swedish,
        popular: true,
        flag: ISOCountryCode.Sweden
    },
    {   name: "Swedish",
        countryCode: ISOCountryCode.Finland,
        code: ISOLanguageCode.SwedishFinland,
        flag: ISOCountryCode.Finland
    },
    {   name: "Swedish",
        countryCode: ISOCountryCode.Sweden,
        code: ISOLanguageCode.SwedishSweden,
        flag: ISOCountryCode.Sweden
    },
    {   name: "Syriac",
        general: true,
        code: ISOLanguageCode.Syriac,
        popular: true,
        flag: ISOCountryCode.Syria
    },
    {   name: "Tajik",
        general: true,
        code: ISOLanguageCode.Tajik,
        flag: ISOCountryCode.Tajikistan
    },
    {   name: "Tamil",
        general: true,
        code: ISOLanguageCode.Tamil,
        flag: ISOCountryCode.Singapore
    },
    {   name: "Tatar",
        general: true,
        code: ISOLanguageCode.Tatar,
        flag: ISOCountryCode.RussianFederation
    },
    {   name: "Telugu",
        general: true,
        code: ISOLanguageCode.Telugu,
        flag: ISOCountryCode.India
    },
    {   name: "Thai",
        general: true,
        code: ISOLanguageCode.Thai,
        popular: true,
        flag: ISOCountryCode.Thailand
    },
    {   name: "Tibetan",
        general: true,
        code: ISOLanguageCode.Tibetan,
        popular: true,
        flag: ISOCountryCode.Bhutan
    },
    {   name: "Tigrinya",
        general: true,
        code: ISOLanguageCode.Tigrinya,
        flag: ISOCountryCode.Ethiopia
    },
    {   name: "Tsonga",
        general: true,
        code: ISOLanguageCode.Tsonga,
        flag: ISOCountryCode.SouthAfrica
    },
    {   name: "Turkish",
        general: true,
        code: ISOLanguageCode.Turkish,
        popular: true,
        flag: ISOCountryCode.Turkey
    },
    {   name: "Turkmen",
        general: true,
        code: ISOLanguageCode.Turkmen,
        popular: true,
        flag: ISOCountryCode.Turkmenistan
    },
    {   name: "Tuvalan",
        general: true,
        code: ISOLanguageCode.Tuvalan,
        popular: true,
        flag: ISOCountryCode.Tuvalu
    },
    {   name: "Ukrainian",
        general: true,
        code: ISOLanguageCode.Ukrainian,
        popular: true,
        flag: ISOCountryCode.Ukraine
    },
    {   name: "Urdu",
        general: true,
        code: ISOLanguageCode.Urdu,
        flag: ISOCountryCode.Pakistan
    },
    {   name: "Uzbek",
        general: true,
        code: ISOLanguageCode.Uzbek,
        popular: true,
        flag: ISOCountryCode.Uzbekistan
    },
    {   name: "Vietnamese",
        general: true,
        code: ISOLanguageCode.Vietnamese,
        popular: true,
        flag: ISOCountryCode.Vietnam
    },
    {   name: "Welsh",
        general: true,
        code: ISOLanguageCode.Welsh,
        flag: ISOCountryCode.Wales
    },
    {   name: "Xhosa",
        general: true,
        code: ISOLanguageCode.Xhosa,
        flag: ISOCountryCode.SouthAfrica
    },
    {   name: "Yiddish",
        general: true,
        code: ISOLanguageCode.Yiddish,
        flag: ISOCountryCode.Israel
    },
    {   name: "Zulu",
        general: true,
        code: ISOLanguageCode.Zulu,
        flag: ISOCountryCode.SouthAfrica
    }
];